export const routes = {
  home: {
    index: '/',
    contact: '/#contact',
    about_us: '/#about_us',
    login: '/login',
    register: 'register',
    performance_test: '/test'
  },
  eCommerce: {
    dashboard: '/dashboard/ecommerce',
    products: '/dashboard/ecommerce/products',
    createProduct: '/dashboard/ecommerce/products/create',
    productDetails: (id: string) => `/ecommerce/products/${id}`,
    ediProduct: (id: string) => `/ecommerce/products/${id}/edit`,
    categories: '/dashboard/ecommerce/categories',
    createCategory: '/dashboard/ecommerce/categories/create',
    editCategory: (id: string) => `/ecommerce/categories/${id}/edit`,
    orders: '/dashboard/ecommerce/orders',
    createOrder: '/dashboard/ecommerce/orders/create',
    orderDetails: (id: string) => `/ecommerce/orders/${id}`,
    editOrder: (id: string) => `/ecommerce/orders/${id}/edit`,
    reviews: '/dashboard/ecommerce/reviews',
    shop: '/dashboard/ecommerce/shop',
    cart: '/dashboard/ecommerce/cart',
    checkout: '/dashboard/ecommerce/checkout',
    trackingId: (id: string) => `/ecommerce/tracking/${id}`,
  },
  support: {
    dashboard: '/dashboard/support',
    inbox: '/dashboard/support/inbox',
    supportCategory: (category: string) => `/support/inbox/${category}`,
    messageDetails: (id: string) => `/support/inbox/${id}`,
    snippets: '/dashboard/support/snippets',
    createSnippet: '/dashboard/support/snippets/create',
    viewSnippet: (id: string) => `/support/snippets/${id}`,
    editSnippet: (id: string) => `/support/snippets/${id}/edit`,
    templates: '/dashboard/support/templates',
    createTemplate: '/dashboard/support/templates/create',
    viewTemplate: (id: string) => `/support/templates/${id}`,
    editTemplate: (id: string) => `/support/templates/${id}/edit`,
  },
  logistics: {
    dashboard: '/dashboard/logistics',
    shipmentList: '/dashboard/logistics/shipments',
    customerProfile: '/dashboard/logistics/customer-profile',
    createShipment: '/dashboard/logistics/shipments/create',
    editShipment: (id:string)=>`/logistics/shipments/${id}/edit`,
    shipmentDetails: (id:string)=>`/logistics/shipments/${id}`,
    tracking: (id: string) => `/logistics/tracking/${id}`,
  },
  analytics: '/dashboard/analytics',
  file: {
    dashboard: '/dashboard/file',
    manager: '/dashboard/file-manager',
    upload: '/dashboard/file-manager/upload',
    create: '/dashboard/file-manager/create',
  },
  invoice: {
    home: '/dashboard/invoice',
    create: '/dashboard/invoice/create',
    details: (id: string) => `/invoice/${id}`,
    edit: (id: string) => `/invoice/${id}/edit`,
  },
  widgets: {
    cards: '/dashboard/widgets/cards',
    icons: '/dashboard/widgets/icons',
    charts: '/dashboard/widgets/charts',
    maps: '/dashboard/widgets/maps',
    banners: '/dashboard/widgets/banners',
  },
  tables: {
    basic: '/dashboard/tables/basic',
    collapsible: '/dashboard/tables/collapsible',
    enhanced: '/dashboard/tables/enhanced',
    pagination: '/dashboard/tables/pagination',
    search: '/dashboard/tables/search',
    stickyHeader: '/dashboard/tables/sticky-header',
  },
  multiStep: '/dashboard/multi-step',
  forms: {
    profileSettings: '/dashboard/forms/profile-settings',
    notificationPreference: '/dashboard/forms/profile-settings/notification',
    personalInformation: '/dashboard/forms/profile-settings/profile',
    newsletter: '/dashboard/forms/newsletter',
  },
  search: {
    realEstate: '/dashboard/search/real-estate',
  },




  profile: '/profile',
  welcome: '/welcome',
  comingSoon: '/coming-soon',
  accessDenied: '/access-denied',
  notFound: '/not-found',
  maintenance: '/maintenance',
  blank: '/blank',
  auth: {
    signUp1: '/auth/sign-up-1',
    signUp2: '/auth/sign-up-2',
    signUp3: '/auth/sign-up-3',
    signUp4: '/auth/sign-up-4',
    signUp5: '/auth/sign-up-5',
    // sign in
    signIn1: '/auth/sign-in-1',
    signIn2: '/auth/sign-in-2',
    signIn3: '/auth/sign-in-3',
    signIn4: '/auth/sign-in-4',
    signIn5: '/auth/sign-in-5',
    // forgot password
    forgotPassword1: '/auth/forgot-password-1',
    forgotPassword2: '/auth/forgot-password-2',
    forgotPassword3: '/auth/forgot-password-3',
    forgotPassword4: '/auth/forgot-password-4',
    forgotPassword5: '/auth/forgot-password-5',
    // OTP
    otp1: '/auth/otp-1',
    otp2: '/auth/otp-2',
    otp3: '/auth/otp-3',
    otp4: '/auth/otp-4',
    otp5: '/auth/otp-5',
  },
  signIn: '/signin',
};
